name: Bench
run-name: Bench
on: push
defaults:
  run:
    shell: bash
jobs:
  bench:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2' # The Go version to download (if necessary) and use.

      - name: Initialize Data
        run: |
          cd initial-data
          pwd

          echo "::group:: pip install"
          pip install -r requirements.txt
          echo "::endgroup::"
          
          echo "::group:: go install "
          go install github.com/orisano/wayt@latest
          echo "::endgroup::"
          
          echo "::group:: make"
          make
          echo "::endgroup::"

          cd ..
      
      - name: Webapp
        run: |
          cd webapp
          make api-server/go
          cd ..

      - name: Bench
        run: |
          cd bench
          make
          ./bench
